### ISSUE TITLE
[UAT] Release checklist version 1.1.9

### ISSUE THREAD

**Issue by gaupoit** [CasperDash/casperdash-mobile-wallet#172]
**Is your feature request related to a problem? Please describe.**

I. Android

- [x] Transfer CSPR with Transfer ID
- [x] Import Casper Wallet 
- [x] Send/Receive CSPR with new imported Casper Wallet
- [x] [Import Casper Wallet] Import pem file to Casper Dash

II. iOS

- [x] Transfer CSPR with Transfer ID
- [x] Import Casper Wallet 
- [x] Send/Receive CSPR with new imported Casper Wallet
- [x] [Import Casper Wallet] Import pem file to Casper Dash
